In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
user = pd.read_csv('/Users/sitt1iu/Documents/Kris/电商用户行为可视化分析/fresh_comp_offline/tianchi_fresh_comp_train_user.csv')
user

,user_id,item_id,behavior_type,user_geohash,item_category,time
0,10001082,285259775,1,97lk14c,4076,2014-12-08 18
1,10001082,4368907,1,NaN,5503,2014-12-12 12
2,10001082,53616768,4,NaN,9762,2014-12-02 15
3,10001082,9947871,1,NaN,2825,2014-11-28 20
4,10001082,150720867,1,95qoghe,3200,2014-12-15 08
...,...,...,...,...,...,...
15463105,65341491,259008790,1,NaN,13164,2014-12-03 12
15463106,65341491,336404938,1,NaN,13164,2014-12-03 12
15463107,65341491,52142024,1,95qhbsu,5201,2014-12-10 22
15463108,65341491,250557965,1,NaN,13164,2014-12-03 12
15463109,65341491,300315408,1,NaN,1838,2014-11-29 08

In [3]:
user.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15463110 entries, 0 to 15463109
Data columns (total 6 columns):
 #   Column         Dtype
---  ------         -----
 0   user_id        int64
 1   item_id        int64
 2   behavior_type  int64
 3   user_geohash   object
 4   item_category  int64
 5   time           object
dtypes: int64(4), object(2)
memory usage: 707.8+ MB

In [5]:
user.describe()

            user_id       item_id  behavior_type  item_category
count  1.546311e+07  1.546311e+07   1.546311e+07   1.546311e+07
mean   7.015207e+07  2.023169e+08   1.153780e+00   6.827181e+03
std    4.572019e+07  1.167524e+08   5.440445e-01   3.810410e+03
min    4.920000e+02  3.700000e+01   1.000000e+00   2.000000e+00
25%    3.021406e+07  1.014015e+08   1.000000e+00   3.687000e+03
50%    5.638708e+07  2.022669e+08   1.000000e+00   6.054000e+03
75%    1.166482e+08  3.035247e+08   1.000000e+00   1.025800e+04
max    1.424430e+08  4.045625e+08   4.000000e+00   1.408000e+04

In [6]:
user.isnull().sum()

user_id                0
item_id                0
behavior_type          0
user_geohash     8207386
item_category          0
time                   0
dtype: int64

In [7]:
user.drop_duplicates(keep = 'last', inplace = True)

In [9]:
print(user['time'].dtype)
print(user['time'].head())

object
0    2014-12-08 18
1    2014-12-12 12
2    2014-12-02 15
3    2014-11-28 20
4    2014-12-15 08
Name: time, dtype: object

In [ ]:
user['time'] = pd.to_datetime(user['time'])  

user['dates'] = user.time.dt.date
user['month'] = user.dates.values.astype('datetime64[M]')
user['hours'] = user.time.dt.hour

In [12]:
pv_day = user[user.behavior_type == 1].groupby('dates')['behavior_type'].count()
pv_day

dates
2014-11-18    395982
2014-11-19    405103
2014-11-20    392599
2014-11-21    372570
2014-11-22    390638
2014-11-23    428205
2014-11-24    420721
2014-11-25    403631
2014-11-26    397048
2014-11-27    404786
2014-11-28    383756
2014-11-29    398341
2014-11-30    438904
2014-12-01    435448
2014-12-02    440729
2014-12-03    457803
2014-12-04    431818
2014-12-05    400873
2014-12-06    455632
2014-12-07    478213
2014-12-08    481243
2014-12-09    494873
2014-12-10    510422
2014-12-11    612238
2014-12-12    833019
2014-12-13    494372
2014-12-14    500450
2014-12-15    489105
2014-12-16    476857
2014-12-17    468700
2014-12-18    459362
Name: behavior_type, dtype: int64

In [15]:
uv_day = user[user.behavior_type == 1].groupby('dates')['user_id'].nunique()

In [16]:
uv_day

dates
2014-11-18    12530
2014-11-19    12591
2014-11-20    12520
2014-11-21    12292
2014-11-22    12170
2014-11-23    12602
2014-11-24    12742
2014-11-25    12564
2014-11-26    12426
2014-11-27    12365
2014-11-28    12157
2014-11-29    12161
2014-11-30    12503
2014-12-01    12803
2014-12-02    12796
2014-12-03    12953
2014-12-04    12842
2014-12-05    12605
2014-12-06    12642
2014-12-07    12933
2014-12-08    12963
2014-12-09    12953
2014-12-10    13070
2014-12-11    13764
2014-12-12    15306
2014-12-13    13318
2014-12-14    13188
2014-12-15    13426
2014-12-16    13260
2014-12-17    13042
2014-12-18    12965
Name: user_id, dtype: int64

In [18]:
import pyecharts.options as opts
from pyecharts.charts import Line
from pyecharts.charts import Grid
import numpy as np

In [30]:
attr = list(pv_day.index)
pv = (
    Line(init_opts = opts.InitOpts(width = '1000px', height = '500px'))
    .add_xaxis(xaxis_data = attr)
    .add_yaxis(
        series_name = 'pv',
        y_axis = np.around(pv_day.values/10000, decimals = 2),
        label_opts = opts.LabelOpts(is_show = False)
    )
    .add_yaxis(
        series_name = 'uv',
        yaxis_index = 1,
        y_axis = np.around(uv_day.values/10000, decimals = 2),
        label_opts = opts.LabelOpts(is_show = False)
    )
    .extend_axis(
        yaxis = opts.AxisOpts(
            name = 'uv',
            type_ = 'value',
            min_ = 0,
            max_ = 1.6,
            interval = 0.4,
            axislabel_opts = opts.LabelOpts(formatter = '{value}万人')
        )
    )
    .set_global_opts(
        tooltip_opts = opts.TooltipOpts(
            is_show = True, trigger = 'axis', axis_pointer_type = 'cross'
        ),
        xaxis_opts = opts.AxisOpts(
            type_ = 'category',
            axispointer_opts = opts.AxisPointerOpts(is_show = True, type_ = 'shadow')
        ),
        yaxis_opts = opts.AxisOpts(
            name = 'pv',
            type_ = 'value',
            min_ = 0,
            max_ = 100,
            interval = 20,
            axislabel_opts = opts.LabelOpts(formatter = '{value}万次'),
            axistick_opts = opts.AxisTickOpts(is_show = True),
            splitline_opts = opts.SplitLineOpts(is_show = True)
        ),
        title_opts = opts.TitleOpts(title = 'pv与uv趋势图')
    )
)

In [33]:
from pyecharts.globals import CurrentConfig, NotebookType
CurrentConfig.NOTEBOOK_TYPE = NotebookType.JUPYTER_LAB

In [34]:
pv.load_javascript()

In [36]:
pv.render('/Users/sitt1iu/Downloads/pv_uv.html')

'/Users/sitt1iu/Downloads/pv_uv.html'

In [37]:
from IPython.display import IFrame
IFrame('/Users/sitt1iu/Downloads/pv_uv.html', width=1000, height=500)

In [38]:
pv_uv = pd.concat([pv_day, uv_day], join = 'outer', axis = 1)
pv_uv.columns = ['pv_day', 'uv_day']

new_day = pv_uv.diff()
new_day.columns = ['new_pv', 'new_uv']
new_day

              new_pv  new_uv
dates
2014-11-18       NaN     NaN
2014-11-19    9121.0    61.0
2014-11-20  -12504.0   -71.0
2014-11-21  -20029.0  -228.0
2014-11-22   18068.0  -122.0
2014-11-23   37567.0   432.0
2014-11-24   -7484.0   140.0
2014-11-25  -17090.0  -178.0
2014-11-26   -6583.0  -138.0
2014-11-27    7738.0   -61.0
2014-11-28  -21030.0  -208.0
2014-11-29   14585.0     4.0
2014-11-30   40563.0   342.0
2014-12-01   -3456.0   300.0
2014-12-02    5281.0    -7.0
2014-12-03   17074.0   157.0
2014-12-04  -25985.0  -111.0
2014-12-05  -30945.0  -237.0
2014-12-06   54759.0    37.0
2014-12-07   22581.0   291.0
2014-12-08    3030.0    30.0
2014-12-09   13630.0   -10.0
2014-12-10   15549.0   117.0
2014-12-11  101816.0   694.0
2014-12-12  220781.0  1542.0
2014-12-13 -338647.0 -1988.0
2014-12-14    6078.0  -130.0
2014-12-15  -11345.0   238.0
2014-12-16  -12248.0  -166.0
2014-12-17   -8157.0  -218.0
2014-12-18   -9338.0   -77.0

In [42]:
attr = new_day.index
v = new_day.new_uv
w = new_day.new_pv

li = (
    Line(init_opts = opts.InitOpts(width = '1000px', height = '500px'))
    .add_xaxis(xaxis_data = attr)
    .add_yaxis(
        '新增pv',
        w,
        label_opts = opts.LabelOpts(is_show = False)
    )
    .extend_axis(
        yaxis = opts.AxisOpts(
            name = '新增uv',
            type_ = 'value',
            min_ = -2000,
            max_ = 1600,
            interval = 400,
            axislabel_opts = opts.LabelOpts(formatter = '{value}')
        )
    )
    .set_global_opts(
        tooltip_opts = opts.TooltipOpts(
            is_show = True, trigger = 'axis', axis_pointer_type = 'cross'
        ),
        xaxis_opts = opts.AxisOpts(
            type_ = 'category',
            axispointer_opts = opts.AxisPointerOpts(is_show = True, type_ = 'shadow')
        ),
        yaxis_opts = opts.AxisOpts(
            name = '新增pv',
            type_ = 'value',
            min_ = -350000,
            max_ = 250000,
            interval = 100000,
            axislabel_opts = opts.LabelOpts(formatter = '{value}'),
            axistick_opts = opts.AxisTickOpts(is_show = True),
            splitline_opts = opts.SplitLineOpts(is_show = True)
        ),
        title_opts = opts.TitleOpts(title = 'pv, uv差异分析')
    )
)
il = (
    Line()
    .add_xaxis(xaxis_data = attr)
    .add_yaxis('新增uv', v, yaxis_index = '1', label_opts = opts.LabelOpts(is_show = False))
)
c = li.overlap(il)
c.render_notebook()

In [43]:
pv.load_javascript()

In [44]:
pv.render('/Users/sitt1iu/Downloads/pv_uv_diff.html')

'/Users/sitt1iu/Downloads/pv_uv_diff.html'

In [46]:
shopping_cart = user[user.behavior_type == 3].groupby('dates')['behavior_type'].count()
shopping_cart

dates
2014-11-18    18703
2014-11-19    18137
2014-11-20    17883
2014-11-21    17310
2014-11-22    17323
2014-11-23    18842
2014-11-24    18676
2014-11-25    19162
2014-11-26    17282
2014-11-27    17311
2014-11-28    16471
2014-11-29    17494
2014-11-30    20126
2014-12-01    20584
2014-12-02    21770
2014-12-03    22197
2014-12-04    20298
2014-12-05    19931
2014-12-06    20193
2014-12-07    20885
2014-12-08    21459
2014-12-09    22083
2014-12-10    23254
2014-12-11    30137
2014-12-12    46593
2014-12-13    19724
2014-12-14    20131
2014-12-15    19315
2014-12-16    19684
2014-12-17    19082
2014-12-18    18095
Name: behavior_type, dtype: int64

In [47]:
collect = user[user.behavior_type == 2].groupby('dates')['behavior_type'].count()
collect

dates
2014-11-18    13205
2014-11-19    13432
2014-11-20    13111
2014-11-21    12606
2014-11-22    12975
2014-11-23    14529
2014-11-24    13874
2014-11-25    13275
2014-11-26    13530
2014-11-27    13850
2014-11-28    13328
2014-11-29    13545
2014-11-30    14715
2014-12-01    14335
2014-12-02    15312
2014-12-03    16378
2014-12-04    15586
2014-12-05    14517
2014-12-06    15148
2014-12-07    16247
2014-12-08    15771
2014-12-09    15773
2014-12-10    15185
2014-12-11    16817
2014-12-12    19811
2014-12-13    14585
2014-12-14    15782
2014-12-15    15171
2014-12-16    14498
2014-12-17    14783
2014-12-18    13805
Name: behavior_type, dtype: int64

In [48]:
buy = user[user.behavior_type == 4].groupby('dates')['behavior_type'].count()
buy

dates
2014-11-18     6115
2014-11-19     5859
2014-11-20     5787
2014-11-21     5701
2014-11-22     5762
2014-11-23     6011
2014-11-24     6337
2014-11-25     6304
2014-11-26     5968
2014-11-27     6234
2014-11-28     5563
2014-11-29     5764
2014-11-30     6382
2014-12-01     6500
2014-12-02     6642
2014-12-03     6919
2014-12-04     6531
2014-12-05     5587
2014-12-06     6034
2014-12-07     6049
2014-12-08     6172
2014-12-09     5927
2014-12-10     6166
2014-12-11     6273
2014-12-12    28234
2014-12-13     6428
2014-12-14     6306
2014-12-15     6786
2014-12-16     6800
2014-12-17     6530
2014-12-18     6384
Name: behavior_type, dtype: int64

In [49]:
attr_a = list(shopping_cart.index)
v_1 = shopping_cart.values.tolist()
v_2 = collect.values.tolist()
v_3 = buy.values.tolist()

In [51]:
b = (
    Line()
    .add_xaxis(xaxis_data = attr_a)
    .add_yaxis(
        '加购人数',
        v_2,
        label_opts = opts.LabelOpts(is_show = False)
    )
    .add_yaxis(
        '收藏人数',
        v_2,
        label_opts = opts.LabelOpts(is_show = False)
    )
    .add_yaxis(
        '购买人数',
        v_3,
        label_opts = opts.LabelOpts(is_show = False)
    )
    .set_global_opts(title_opts = opts.TitleOpts(title = '不同时期用户行为数据'))
)
b.render_notebook()

In [52]:
b.load_javascript()

In [53]:
b.render('/Users/sitt1iu/Downloads/b.html')

'/Users/sitt1iu/Downloads/b.html'

In [54]:
user['dates'] = pd.to_datetime(user['dates'])

In [56]:
active = user[user['dates'].isin(['2014/12/11', '2014/12/12', '2014/12/13'])]
active

/var/folders/qq/vf4mp42511bcly15v2wxbf980000gn/T/ipykernel_79193/3867132981.py:1: FutureWarning: The behavior of 'isin' with dtype=datetime64[ns] and castable values (e.g. strings) is deprecated. In a future version, these will not be considered matching by isin. Explicitly cast to the appropriate dtype before calling isin instead.
  active = user[user['dates'].isin(['2014/12/11', '2014/12/12', '2014/12/13'])]

,user_id,item_id,behavior_type,user_geohash,item_category,time,dates,month,hours
1,10001082,4368907,1,NaN,5503,2014-12-12 12:00:00,2014-12-12,2014-12-01,12
6,10001082,266563343,1,95qobus,5232,2014-12-12 11:00:00,2014-12-12,2014-12-01,11
17,10001082,29558680,1,95qob0m,5232,2014-12-12 11:00:00,2014-12-12,2014-12-01,11
20,10001082,222375145,1,95qobv6,5503,2014-12-12 11:00:00,2014-12-12,2014-12-01,11
26,10001082,151466952,1,NaN,5232,2014-12-12 11:00:00,2014-12-12,2014-12-01,11
...,...,...,...,...,...,...,...,...,...
15463063,65341491,234065269,1,NaN,5643,2014-12-11 07:00:00,2014-12-11,2014-12-01,7
15463081,65341491,128927836,1,NaN,12510,2014-12-11 07:00:00,2014-12-11,2014-12-01,7
15463090,65341491,141457412,1,NaN,10961,2014-12-12 06:00:00,2014-12-12,2014-12-01,6
15463092,65341491,309130576,1,NaN,11721,2014-12-11 07:00:00,2014-12-11,2014-12-01,7
15463097,65341491,42748021,1,NaN,12510,2014-12-11 07:00:00,2014-12-11,2014-12-01,7

In [57]:
daily = user[~user['dates'].isin(['2014/12/11', '2014/12/12','2014/12/13'])]
daily

/var/folders/qq/vf4mp42511bcly15v2wxbf980000gn/T/ipykernel_79193/2845496206.py:1: FutureWarning: The behavior of 'isin' with dtype=datetime64[ns] and castable values (e.g. strings) is deprecated. In a future version, these will not be considered matching by isin. Explicitly cast to the appropriate dtype before calling isin instead.
  daily = user[~user['dates'].isin(['2014/12/11', '2014/12/12','2014/12/13'])]

,user_id,item_id,behavior_type,user_geohash,item_category,time,dates,month,hours
0,10001082,285259775,1,97lk14c,4076,2014-12-08 18:00:00,2014-12-08,2014-12-01,18
2,10001082,53616768,4,NaN,9762,2014-12-02 15:00:00,2014-12-02,2014-12-01,15
3,10001082,9947871,1,NaN,2825,2014-11-28 20:00:00,2014-11-28,2014-11-01,20
4,10001082,150720867,1,95qoghe,3200,2014-12-15 08:00:00,2014-12-15,2014-12-01,8
5,10001082,97441652,1,NaN,10576,2014-11-20 21:00:00,2014-11-20,2014-11-01,21
...,...,...,...,...,...,...,...,...,...
15463105,65341491,259008790,1,NaN,13164,2014-12-03 12:00:00,2014-12-03,2014-12-01,12
15463106,65341491,336404938,1,NaN,13164,2014-12-03 12:00:00,2014-12-03,2014-12-01,12
15463107,65341491,52142024,1,95qhbsu,5201,2014-12-10 22:00:00,2014-12-10,2014-12-01,22
15463108,65341491,250557965,1,NaN,13164,2014-12-03 12:00:00,2014-12-03,2014-12-01,12
15463109,65341491,300315408,1,NaN,1838,2014-11-29 08:00:00,2014-11-29,2014-11-01,8

In [58]:
from pyecharts.charts import Bar

In [60]:
cart_h = active[active.behavior_type == 3].groupby('hours')['behavior_type'].count()
collect_h = active[active.behavior_type == 2].groupby('hours')['behavior_type'].count()
buy_h = active[active.behavior_type == 4].groupby('hours')['behavior_type'].count()
uv_h = active[active.behavior_type == 1].groupby('hours')['user_id'].count()

In [61]:
attr_h = list(cart_h.index)
h1 = np.around(cart_h.values / 3, decimals = 0).tolist()
h2 = np.around(collect_h.values / 3, decimals = 0).tolist()
h3 = np.around(buy_h.values / 3, decimals = 0).tolist()
h4 = np.around(uv_h.values / 3, decimals = 0).tolist()

In [73]:
h = (
    Line(init_opts = opts.InitOpts(width = '1000px', height = '500px'))
    .add_xaxis(xaxis_data = attr_h)
    .add_yaxis(
        '加购人数',
        h1,
        label_opts = opts.LabelOpts(is_show = False)
    )
    .add_yaxis(
        '收藏人数',
        h2,
        label_opts = opts.LabelOpts(is_show = False)
    )
    .add_yaxis(
        '购买人数',
        h3,
        label_opts = opts.LabelOpts(is_show = False)
    )
    .set_global_opts(
        xaxis_opts = opts.AxisOpts(axislabel_opts = opts.LabelOpts(rotate = 15)),
        title_opts = opts.TitleOpts(title = '日均各时间段活动用户行为', pos_top = '55%'),
        legend_opts = opts.LegendOpts(pos_top = '90%')
    )
)
bar = (
    Bar()
    .add_xaxis(xaxis_data = attr_h)
    .add_yaxis(
        '浏览人数',
        h4,
        label_opts = opts.LabelOpts(is_show = False)
    )
    .set_global_opts(
        title_opts = opts.TitleOpts(title = '活动pv对比数据'),
        legend_opts = opts.LegendOpts(pos_top = '40%')
    )
)

ggrid = (
    Grid()
    .add(bar, grid_opts = opts.GridOpts(pos_bottom = '70%'))
    .add(h, grid_opts = opts.GridOpts(pos_top = '70%'))
)
ggrid.render_notebook()

In [74]:
ggrid.load_javascript()

In [75]:
ggrid.render('/Users/sitt1iu/Downloads/ggrid.html')

'/Users/sitt1iu/Downloads/ggrid.html'

In [76]:
cart_d = daily[daily.behavior_type == 3].groupby('hours')['behavior_type'].count()
collect_d = daily[daily.behavior_type == 2].groupby('hours')['behavior_type'].count()
buy_d = daily[daily.behavior_type == 4].groupby('hours')['behavior_type'].count()
uv_d = daily[daily.behavior_type == 1].groupby('hours')['user_id'].count()

In [78]:
attr_d = list(cart_d.index)
d1 = np.around(cart_d.values / 28, decimals = 0).tolist()
d2 = np.around(collect_d.values / 28, decimals = 0).tolist()
d3 = np.around(buy_d.values / 28, decimals = 0).tolist()
d4 = np.around(uv_d.values / 28, decimals = 0).tolist()

In [79]:
d = (
    Line(init_opts = opts.InitOpts(width = '1000px', height = '500px'))
    .add_xaxis(xaxis_data = attr_d)
    .add_yaxis(
        '加购人数',
        d1,
        label_opts = opts.LabelOpts(is_show = False)
    )
    .add_yaxis(
        '收藏人数',
        d2,
        label_opts = opts.LabelOpts(is_show = False)
    )
    .add_yaxis(
        '购买人数',
        d3,
        label_opts = opts.LabelOpts(is_show = False)
    )
    .set_global_opts(
        xaxis_opts = opts.AxisOpts(axislabel_opts = opts.LabelOpts(rotate = 15)),
        title_opts = opts.TitleOpts(title = '日均各时间段活动用户行为', pos_top = '55%'),
        legend_opts = opts.LegendOpts(pos_top = '90%')
    )
)
y = (
    Bar()
    .add_xaxis(xaxis_data = attr_d)
    .add_yaxis(
        '浏览人数',
        d4,
        label_opts = opts.LabelOpts(is_show = False)
    )
    .set_global_opts(
        title_opts = opts.TitleOpts(title = '日常pv对比数据'),
        legend_opts = opts.LegendOpts(pos_top = '40%')
    )
)

ggrid2 = (
    Grid()
    .add(y, grid_opts = opts.GridOpts(pos_bottom = '70%'))
    .add(d, grid_opts = opts.GridOpts(pos_top = '70%'))
)
ggrid2.render_notebook()

In [80]:
ggrid2.load_javascript()

In [81]:
ggrid2.render('/Users/sitt1iu/Downloads/ggrid2.html')

'/Users/sitt1iu/Downloads/ggrid2.html'

In [82]:
# purchase rate during events
hour_buy_user_num = active[active.behavior_type == 4].drop_duplicates(['user_id', 'dates', 'hours']).groupby(['hours'])['behavior_type'].count()
hour_active_user_num = active.drop_duplicates(['user_id', 'dates', 'hours']).groupby(['hours'])['behavior_type'].count()
hour_buy_rate = hour_buy_user_num / hour_active_user_num
attr_o = list(hour_buy_user_num.index)
vo_2 = np.around(hour_buy_rate.values, decimals = 2)

In [83]:
# daily purchase rate
hour_buy_daily_num = daily[daily.behavior_type == 4].drop_duplicates(['user_id', 'dates', 'hours']).groupby(['hours'])['behavior_type'].count()
hour_active_daily_num = daily.drop_duplicates(['user_id', 'dates', 'hours']).groupby(['hours'])['behavior_type'].count()
daily_buy_rate = hour_buy_daily_num / hour_active_daily_num
attr_o = list(hour_buy_user_num.index)
vi_2 = np.around(daily_buy_rate.values, decimals = 2)

In [85]:
hub = (
    Line()
    .add_xaxis(xaxis_data = attr_o)
    .add_yaxis(
        '日常购买率',
        vi_2,
    )
    .add_yaxis(
        '活动购买率',
        vo_2
    )
    .set_global_opts(title_opts = opts.TitleOpts(title = '不同时段购买率'))
)

hub.render_notebook()

In [86]:
hub.load_javascript()

In [87]:
hub.render('/Users/sitt1iu/Downloads/hub.html')

'/Users/sitt1iu/Downloads/hub.html'

In [88]:
from pyecharts.charts import Funnel

In [89]:
a_pv = active[active.behavior_type == 1]['user_id'].count()
a_cart = active[active.behavior_type == 3]['user_id'].count()
a_collect = active[active.behavior_type == 2]['user_id'].count()
a_buy = active[active.behavior_type == 4]['user_id'].count()

In [90]:
a_attr = ['点击', '加入购物车','收藏','购买']
values = [np.around((a_pv / a_pv * 100), 2),
          np.around((a_cart / a_pv * 100), 2),
          np.around((a_collect / a_pv * 100), 2),
          np.around((a_buy / a_pv * 100), 2)]
data = [[a_attr[i], values[i]] for i in range(len(a_attr))]

In [91]:
a = (
    Funnel()
    .add(
        series_name="用户行为",
        data_pair=data,
        gap=2,
        tooltip_opts=opts.TooltipOpts(trigger="item", formatter="{a} <br/>{b} : {c}%"),
        label_opts=opts.LabelOpts(is_show=True, position="outside"),
        itemstyle_opts=opts.ItemStyleOpts(border_color="#fff", border_width=1),
    )
    .set_global_opts(
        title_opts=opts.TitleOpts(title="用户转化漏斗", subtitle="活动期间用户行为转化率")
    )
)

a.render_notebook()

In [92]:
a.load_javascript()

In [93]:
a.render('/Users/sitt1iu/Downloads/a.html')

'/Users/sitt1iu/Downloads/a.html'

In [94]:
# 日常转化
l_pv = daily[daily.behavior_type == 1]['user_id'].count()
l_cart = daily[daily.behavior_type == 3]['user_id'].count()
l_collect = daily[daily.behavior_type == 2]['user_id'].count()
l_buy = daily[daily.behavior_type == 4]['user_id'].count()

In [95]:
l_attr = ['点击', '加入购物车', '收藏', '购买']
valuel = [np.around((l_pv / l_pv * 100), 2),
          np.around((l_cart / l_pv * 100), 2),
          np.around((l_collect / l_pv * 100), 2),
          np.around((l_buy / l_pv * 100), 2)]

In [96]:
datal = [[l_attr[i], valuel[i]] for i in range(len(l_attr))]

In [98]:
dy = (
    Funnel()
    .add(
        series_name = '用户行为',
        data_pair = datal,
        gap = 2,
        tooltip_opts = opts.TooltipOpts(trigger = 'item', formatter = '{a} <br/> {b} : {c}%'),
        label_opts = opts.LabelOpts(is_show = True, position = 'outside'),
        itemstyle_opts = opts.ItemStyleOpts(border_color = '#fff', border_width = 1)
    )
    .set_global_opts(title_opts = opts.TitleOpts(title = '用户转化漏斗', subtitle = '日常用户行为转化率'))
)
dy.render_notebook()

In [99]:
dy.load_javascript()

In [100]:
dy.render('/Users/sitt1iu/Downloads/dy.html')

'/Users/sitt1iu/Downloads/dy.html'